/*
 * Copyright (c) 2026 The ZMK Behavior Dynamic Macro Contributors
 *
 * SPDX-License-Identifier: MIT
 */

#pragma once

#include <stdbool.h>
#include <stdint.h>

/**
 * @file
 * @brief Runtime control and status API for ZBDM dynamic macros.
 *
 * Slots are zero-based and must be less than CONFIG_ZMK_ZBDM_SLOTS. Event
 * capacity per slot is returned by zmk_zbdm_get_slot_capacity(). All functions
 * use kernel synchronization and must be called from thread context, never an ISR.
 * Mutating functions must not be called from the system workqueue because
 * stopping playback may synchronously cancel work on that queue. Calls made
 * synchronously from an event generated by ZBDM return -EBUSY.
 *
 * When CONFIG_ZMK_ZBDM_PERSIST is enabled, successful recording stops and
 * clears are written to Zephyr settings. A persistence failure for the current
 * operation leaves the RAM value usable, returns the backend error, and is
 * retried by later operations. Earlier failed saves are retried
 * opportunistically; retry failures are logged and remain pending.
 */

/** Clear a slot and begin recording into it.
 *
 * Any recording in another slot is stopped and saved first. Active playback is
 * canceled before recording starts. A pending failed save prevents overwriting
 * the affected slot.
 *
 * @return 0 on success, -EINVAL for an invalid slot, -EBUSY from a generated
 * event, -EAGAIN while a slot save is pending, or a settings backend error.
 */
int zmk_zbdm_record(uint32_t slot);

/** Stop and save the active recording; do nothing while not recording.
 *
 * @return 0 on success, -EBUSY from a generated event, or a settings backend
 * error.
 */
int zmk_zbdm_stop(void);

/** Stop and save when recording this slot; otherwise record this slot.
 *
 * @return The same values as zmk_zbdm_record() or zmk_zbdm_stop().
 */
int zmk_zbdm_toggle(uint32_t slot);

/** Play a non-empty slot.
 *
 * Playback requests do not overlap. A request during recording stops and saves
 * that recording without starting playback. A request during playback is a
 * successful no-op.
 *
 * @return 0 on success or no-op, -EINVAL for an invalid slot, -EBUSY from a
 * generated event or while previous playback work is stopping, -EAGAIN when
 * pressed-usage cleanup is pending, or a settings backend error when the play
 * request stops and saves an active recording.
 */
int zmk_zbdm_play(uint32_t slot);

/** Cancel activity for a slot, clear it, and persist the empty value.
 *
 * Clearing the currently recording or playing slot stops that activity. Other
 * slots' activity is unaffected.
 *
 * @return 0 on success, -EINVAL for an invalid slot, -EBUSY from a generated
 * event, or a settings backend error.
 */
int zmk_zbdm_clear(uint32_t slot);

/** Cancel the active recording and/or playback.
 *
 * A canceled recording restores its previous RAM contents when
 * CONFIG_ZMK_ZBDM_CANCEL_RESTORE is enabled; otherwise it leaves the slot empty
 * in RAM. Canceling never persists the in-progress recording.
 *
 * @return 0 on success or while idle, or -EBUSY from a generated event.
 */
int zmk_zbdm_cancel(void);

/** Return whether a recording is active. Thread context only. */
bool zmk_zbdm_is_recording(void);

/** Return whether playback or its final cleanup is active. Thread context only. */
bool zmk_zbdm_is_playing(void);

/** Get the zero-based recording or playback slot.
 *
 * @return 0 on success, -EINVAL if @p slot is NULL, or -ENOENT while idle.
 */
int zmk_zbdm_get_active_slot(uint32_t *slot);

/** Get a slot's recorded event count.
 *
 * @return 0 on success or -EINVAL for an invalid slot or NULL @p length.
 */
int zmk_zbdm_get_slot_length(uint32_t slot, uint16_t *length);

/** Return CONFIG_ZMK_ZBDM_MAX_EVENTS, the event capacity of each slot. */
uint16_t zmk_zbdm_get_slot_capacity(void);
